CREATE TABLE [dbo].[webpages_Roles] (
    [RoleId]   INT            IDENTITY (1, 1) NOT NULL,
    [RoleName] NVARCHAR (256) NOT NULL,
    CONSTRAINT [PK__webpages__8AFACE1AED2D6BE5] PRIMARY KEY CLUSTERED ([RoleId] ASC),
    CONSTRAINT [UQ__webpages__8A2B6160DD2ABC20] UNIQUE NONCLUSTERED ([RoleName] ASC)
);

